version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: