// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/messenger-auth/cmd/factory"
	"github.com/TemaKut/messenger-auth/internal/app/commands/migration"
	"github.com/TemaKut/messenger-auth/internal/app/config"
)

// Injectors from wire.go:

func InitCommand() (*migration.Command, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, err := factory.ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	postgresDb, cleanup, err := factory.ProvidePostgresDb(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	command := ProvideCommand(postgresDb)
	return command, func() {
		cleanup()
	}, nil
}
