name: Deploy

on:
  push:

jobs:
#  build-and-push-registry:
#    runs-on: self-hosted
#    environment: build-and-push-registry
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
#          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./infra/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/messenger-auth:${{ github.sha }}

  apply-k8s-manifests:
#    needs: build-and-push-registry
#    environment: apply-k8s-manifests
    uses: TemaKut/messenger-k8s/.github/workflows/service-auth-deploy-action.yml@new/auth
    with:
      path-to-root: infra/k8s/
